config/routes.rb
Rails.application.routes.draw do
  resources :service_providers

  namespace :api, defaults: {format: :json}, constraints: { format: 'json' } do
    resources :service_providers do
      collection do
        get :get_service_providers
      end
    end
  end
  root 'service_providers#index'

end

app/models/service_provider.rb
class ServiceProvider < ActiveRecord::Base
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  respond_to :json
end

app/controllers/api/service_providers_controller.rb
class Api::ServiceProvidersController < Api::ApiController	
	# before_action :set_service_provider, only: [:show, :edit, :update, :destroy]
	respond_to :html, :json
	
	def index
  	@service_providers = ServiceProvider.all
  	render json: @service_providers
  end

  def create
    service_provider = ServiceProvider.new
    service_provider.firstname = params[:firstname]
    service_provider.lastname = params[:lastname]

    if service_provider.save
      respond_with(service_provider, :location => api_service_provider_path(service_provider))
    else
      respond_with(service_provider)
    end
  end

  def update
    @service_provider = ServiceProvider.find(params[:id].to_i)    
    firstname = params[:firstname].blank? ? @service_provider.firstname : params[:firstname]
    lastname = params[:lastname].blank? ?  @service_provider.lastname : params[:lastname]
    @service_provider.update_attributes!(:firstname => firstname, :lastname => lastname)
     
    if @service_provider.save
      respond_with(@service_provider, :location => api_service_provider_path(@service_provider))
    else
      respond_with(service_provider)
    end
  end

  def destroy
    @service_provider = ServiceProvider.find(params[:id].to_i)
    @service_provider.destroy  
    respond_with(@service_provider)
  end

  def show
    @service_provider = ServiceProvider.find(params[:id].to_i)
    render json: @service_provider
  end

  def get_service_providers
    query = {}
    @service_providers = []
    if !params[:id].blank?
      query[:id] =  params[:id].to_i
    end
    if !params[:firstname].blank?
      query[:firstname] =  params[:firstname]
    end 
    if !params[:lastname].blank?
      query[:lastname] =  params[:lastname]
    end 

    @service_providers = ServiceProvider.where(query) 
    render json: @service_providers
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  protect_from_forgery with: :null_session
  
  after_filter  :set_csrf_cookie_for_ng, :allow_cors

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end 

  def allow_cors
    headers["Access-Control-Allow-Origin"] = "*"
    headers["Access-Control-Allow-Methods"] = %w{GET POST PUT DELETE}.join(",")
    headers["Access-Control-Allow-Headers"] =
      %w{Origin Accept Content-Type X-Requested-With X-CSRF-Token}.join(",")

    head(:ok) if request.request_method == "OPTIONS"
    
  end


end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  before_action :set_service_provider, only: [:show, :edit, :update, :destroy]

  # GET /service_providers
  # GET /service_providers.json
  def index
    @service_providers = ServiceProvider.all
  end

  # GET /service_providers/1
  # GET /service_providers/1.json
  def show
  end

  # GET /service_providers/new
  def new
    @service_provider = ServiceProvider.new
  end

  # GET /service_providers/1/edit
  def edit
  end

  # POST /service_providers
  # POST /service_providers.json
  def create
    @service_provider = ServiceProvider.new(service_provider_params)

    respond_to do |format|
      if @service_provider.save
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully created.' }
        format.json { render :show, status: :created, location: @service_provider }
      else
        format.html { render :new }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_providers/1
  # PATCH/PUT /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update(service_provider_params)
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_provider }
      else
        format.html { render :edit }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_providers/1
  # DELETE /service_providers/1.json
  def destroy
    @service_provider.destroy
    respond_to do |format|
      format.html { redirect_to service_providers_url, notice: 'Service provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_provider_params
      params.require(:service_provider).permit(:firstname, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GetDoctorAppointment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/service_providers/_form.html.erb
<%= form_for(@service_provider) do |f| %>
  <% if @service_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_provider.errors.count, "error") %> prohibited this service_provider from being saved:</h2>

      <ul>
      <% @service_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_providers/edit.html.erb
<h1>Editing service_provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_provider %> |
<%= link_to 'Back', service_providers_path %>

app/views/service_providers/index.html.erb
<h1>Listing service_providers</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_providers.each do |service_provider| %>
      <tr>
        <td><%= service_provider.firstname %></td>
        <td><%= service_provider.lastname %></td>
        <td><%= link_to 'Show', service_provider %></td>
        <td><%= link_to 'Edit', edit_service_provider_path(service_provider) %></td>
        <td><%= link_to 'Destroy', service_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service provider', new_service_provider_path %>

app/views/service_providers/new.html.erb
<h1>New service_provider</h1>

<%= render 'form' %>

<%= link_to 'Back', service_providers_path %>

app/views/service_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @service_provider.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @service_provider.lastname %>
</p>

<%= link_to 'Edit', edit_service_provider_path(@service_provider) %> |
<%= link_to 'Back', service_providers_path %>